_base_ = ['./ii_generate_world_stage2_history_selective_gate_v1.py']

model = dict(
    history_gate=dict(
        corruption_mode='occstress_style',
        current_corr_ratio=0.65,
        history_corr_ratio=0.65,
        slot_corr_prob=0.6,
        history_strength_init=0.0,
        current_strength_init=0.0,
        history_gate_bias=0.0,
        current_gate_bias=-4.0,
        current_identity_weight=0.08,
        current_denoise_weight=0.15,
        current_gate_supervision_weight=0.03,
        history_gate_supervision_weight=0.03,
        strength_reg_weight=0.001,
        clean_consistency_weight=0.0,
        occstress_style_modes=('dropout', 'hole', 'semantic', 'misalignment'),
        occstress_noise_std=0.05,
        occstress_dropout_channel_drop_prob=0.35,
        occstress_hole_min_block=6,
        occstress_hole_max_block=18,
        occstress_hole_max_blocks=2,
        occstress_misalignment_prob=1.0,
        occstress_max_shift=6,
        occstress_semantic_channel_mix_prob=0.5,
        occstress_semantic_noise_std=0.06,
    ),
)
